from telegram.ext import CommandHandler, CallbackQueryHandler, MessageHandler, Filters
from mercado import *
from cartas import *
from gemas import *
from utils import *

def register_handlers(dispatcher, bot):
    dispatcher.add_handler(CallbackQueryHandler(callback_comprarobj, pattern="^comprarobj_"))
    dispatcher.add_handler(CallbackQueryHandler(callback_ampliar_vender, pattern="^ampliar_vender_"))
    dispatcher.add_handler(CallbackQueryHandler(callback_mejorar_carta, pattern="^mejorar_"))
    dispatcher.add_handler(CallbackQueryHandler(callback_confirmar_mejora, pattern="^(confirmamejora_|cancelarmejora)"))
    dispatcher.add_handler(CallbackQueryHandler(manejador_callback))
    dispatcher.add_handler(CommandHandler('tiendagemas', tienda_gemas))
    dispatcher.add_handler(CommandHandler('darGemas', comando_darGemas))
    dispatcher.add_handler(CommandHandler('gemas', comando_gemas))
    dispatcher.add_handler(CommandHandler('usar', comando_usar))
    dispatcher.add_handler(CommandHandler('apodo', comando_apodo))
    dispatcher.add_handler(CommandHandler('inventario', comando_inventario))
    dispatcher.add_handler(CommandHandler('tienda', comando_tienda))
    dispatcher.add_handler(CommandHandler('comprarobjeto', comando_comprarobjeto))
    dispatcher.add_handler(CommandHandler('idolday', comando_idolday))
    dispatcher.add_handler(CommandHandler('album', comando_album))
    dispatcher.add_handler(CommandHandler('miid', comando_miid))
    dispatcher.add_handler(CommandHandler('bonoidolday', comando_bonoidolday))
    dispatcher.add_handler(CommandHandler('comandos', comando_comandos))
    dispatcher.add_handler(CommandHandler('giveidol', comando_giveidol))
    dispatcher.add_handler(CommandHandler('setsprogreso', comando_setsprogreso))
    dispatcher.add_handler(CommandHandler('set', comando_set_detalle))
    dispatcher.add_handler(MessageHandler(Filters.text & (~Filters.command), handler_regalo_respuesta))
    dispatcher.add_handler(CommandHandler('ampliar', comando_ampliar))
    dispatcher.add_handler(CommandHandler('kponey', comando_saldo))
    dispatcher.add_handler(CommandHandler('darKponey', comando_darKponey))
    dispatcher.add_handler(CommandHandler('fav', comando_fav))
    dispatcher.add_handler(CommandHandler('favoritos', comando_favoritos))
    dispatcher.add_handler(CommandHandler('precio', comando_precio))
    dispatcher.add_handler(CommandHandler('vender', comando_vender))
    dispatcher.add_handler(CommandHandler('mercado', comando_mercado))
    dispatcher.add_handler(CommandHandler('comprar', comando_comprar))
    dispatcher.add_handler(CommandHandler('retirar', comando_retirar))
    dispatcher.add_handler(CommandHandler('mejorar', comando_mejorar))
